# Generated by Django 5.1.5 on 2025-01-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='default_uom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
