# Generated by Django 5.1.5 on 2025-02-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_item_image_alter_itemvariant_item'),
        ('pos', '0004_customer_user'),
    ]

    operations = [
    ]
