# Generated by Django 5.1.5 on 2025-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_posinvoiceitem_item_price_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posinvoice',
            name='invoice_no',
            field=models.CharField(default='10', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
