# Generated by Django 5.1.5 on 2025-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_remove_posinvoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='posinvoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
