# Generated by Django 5.1.5 on 2025-03-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_uom_created_at_uom_updated_at_alter_uom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
