# Generated by Django 5.1.5 on 2025-03-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_alter_uom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posinvoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Overdue', 'Overdue'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
